"""add lead follow-up and task operator

Revision ID: 2ee95126137a
Revises: 0001_baseline
Create Date: 2026-08-30 09:47:43.840666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee95126137a'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_follow_ups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('next_follow_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_follow_ups_created_at'), 'lead_follow_ups', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_follow_ups_lead_id'), 'lead_follow_ups', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_follow_ups_user_id'), 'lead_follow_ups', ['user_id'], unique=False)
    op.add_column('collect_tasks', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_collect_tasks_created_by'), 'collect_tasks', ['created_by'], unique=False)
    op.create_foreign_key(None, 'collect_tasks', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('leads', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('follow_status', sa.String(length=16), nullable=True))
    op.add_column('leads', sa.Column('last_followed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('next_follow_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_leads_follow_status'), 'leads', ['follow_status'], unique=False)
    op.create_index(op.f('ix_leads_owner_id'), 'leads', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_owner_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_follow_status'), table_name='leads')
    op.drop_column('leads', 'next_follow_at')
    op.drop_column('leads', 'last_followed_at')
    op.drop_column('leads', 'follow_status')
    op.drop_column('leads', 'owner_id')
    op.drop_constraint(None, 'collect_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_collect_tasks_created_by'), table_name='collect_tasks')
    op.drop_column('collect_tasks', 'created_by')
    op.drop_index(op.f('ix_lead_follow_ups_user_id'), table_name='lead_follow_ups')
    op.drop_index(op.f('ix_lead_follow_ups_lead_id'), table_name='lead_follow_ups')
    op.drop_index(op.f('ix_lead_follow_ups_created_at'), table_name='lead_follow_ups')
    op.drop_table('lead_follow_ups')
    # ### end Alembic commands ###
