"""whatsapp numbers evidence column + rescore

Revision ID: 6175a9ca77ce
Revises: d2b1e98f091f
Create Date: 2026-08-30 20:00:37.362584

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6175a9ca77ce'
down_revision: str | None = 'd2b1e98f091f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # JSON NOT NULL 加列必须带 server_default（同 b20022d59541 处理）
    op.add_column('leads', sa.Column('whatsapp_numbers', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    # 评分口径变更（CTWA/私域进入 WhatsApp 意向维度 + 多号码加分）→ 全量重算
    _rescore_all()
    # ### end Alembic commands ###


def _rescore_all() -> None:
    """六维重算（评分纯函数；号码列表此刻为空，多号码加分后续富化自动爬升）。"""
    from app.collectors.scoring import score_lead_inputs

    conn = op.get_bind()
    leads_t = sa.Table("leads", sa.MetaData(), autoload_with=conn)
    for row in conn.execute(sa.select(leads_t)).mappings():
        total, dims, grade = score_lead_inputs(
            is_cn=row["is_cn"],
            fb_whatsapp=row["fb_whatsapp"],
            country=row["country"],
            website=row["website"],
            whatsapp_hit=row["whatsapp_hit"],
            whatsapp_url=row["whatsapp_url"],
            whatsapp_job=row["whatsapp_job"],
            scenes=row["scenes"] or [],
            whatsapp_numbers=row["whatsapp_numbers"] or [],
            saas_signals=row["saas_signals"] or {},
            job_urls=row["job_urls"] or [],
            social=row["social"] or {},
            email=row["email"],
            phone_raw=row["phone_raw"],
            phone_e164=row["phone_e164"],
            sources=row["sources"] or [],
        )
        conn.execute(
            sa.update(leads_t)
            .where(leads_t.c.id == row["id"])
            .values(score=total, score_signals=dims, grade=grade)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'whatsapp_numbers')
    # ### end Alembic commands ###
