"""add cn cross-border icp fields

Revision ID: 88366a3fd466
Revises: 2ee95126137a
Create Date: 2026-08-30 14:15:30.634855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88366a3fd466'
down_revision: Union[str, None] = '2ee95126137a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default=flase：存量行补默认值，否则 NOT NULL 加列直接 NotNullViolation
    op.add_column('leads', sa.Column('is_cn', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('leads', sa.Column('fb_whatsapp', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_leads_fb_whatsapp'), 'leads', ['fb_whatsapp'], unique=False)
    op.create_index(op.f('ix_leads_is_cn'), 'leads', ['is_cn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_is_cn'), table_name='leads')
    op.drop_index(op.f('ix_leads_fb_whatsapp'), table_name='leads')
    op.drop_column('leads', 'fb_whatsapp')
    op.drop_column('leads', 'is_cn')
    # ### end Alembic commands ###
