"""lead contacts events grade scenes saas + six-dim rescore

Revision ID: b20022d59541
Revises: 88366a3fd466
Create Date: 2026-08-30 16:02:23.328555

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b20022d59541'
down_revision: str | None = '88366a3fd466'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=128), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('linkedin', sa.String(length=512), nullable=True),
    sa.Column('seniority', sa.String(length=8), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'email', name='uq_lead_contacts_lead_email')
    )
    op.create_index(op.f('ix_lead_contacts_email'), 'lead_contacts', ['email'], unique=False)
    op.create_index(op.f('ix_lead_contacts_lead_id'), 'lead_contacts', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_contacts_seniority'), 'lead_contacts', ['seniority'], unique=False)
    op.create_table('lead_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_events_created_at'), 'lead_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_events_created_by'), 'lead_events', ['created_by'], unique=False)
    op.create_index(op.f('ix_lead_events_event_type'), 'lead_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_lead_events_lead_id'), 'lead_events', ['lead_id'], unique=False)
    op.add_column('leads', sa.Column('grade', sa.String(length=2), server_default='C', nullable=False))
    # JSON NOT NULL 加列必须带 server_default，否则 PG 对已有行直接报错（88366a3fd466 同款处理）
    op.add_column('leads', sa.Column('scenes', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('leads', sa.Column('saas_signals', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
    op.create_index(op.f('ix_leads_grade'), 'leads', ['grade'], unique=False)
    # 存量回填：按六维模型重算 score/score_signals/grade（评分是行属性纯函数；
    # 此刻联系人/场景/SaaS 信号均为空 → contact 维=0，后续富化与联系人录入会自动爬升）
    _backfill_six_dim()
    # ### end Alembic commands ###


def _backfill_six_dim() -> None:
    """全表重算六维评分。回填读 settings.TARGET_REGIONS——用与应用一致的 .env 跑 db-upgrade。"""
    from app.collectors.scoring import score_lead_inputs

    conn = op.get_bind()
    leads_t = sa.Table("leads", sa.MetaData(), autoload_with=conn)
    rows = conn.execute(sa.select(leads_t)).mappings().all()
    for row in rows:
        total, dims, grade = score_lead_inputs(
            is_cn=row["is_cn"],
            fb_whatsapp=row["fb_whatsapp"],
            country=row["country"],
            website=row["website"],
            whatsapp_hit=row["whatsapp_hit"],
            whatsapp_url=row["whatsapp_url"],
            whatsapp_job=row["whatsapp_job"],
            scenes=row["scenes"] or [],
            saas_signals=row["saas_signals"] or {},
            job_urls=row["job_urls"] or [],
            social=row["social"] or {},
            email=row["email"],
            phone_raw=row["phone_raw"],
            phone_e164=row["phone_e164"],
            sources=row["sources"] or [],
        )
        conn.execute(
            sa.update(leads_t)
            .where(leads_t.c.id == row["id"])
            .values(score=total, score_signals=dims, grade=grade)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_grade'), table_name='leads')
    op.drop_column('leads', 'saas_signals')
    op.drop_column('leads', 'scenes')
    op.drop_column('leads', 'grade')
    op.drop_index(op.f('ix_lead_events_lead_id'), table_name='lead_events')
    op.drop_index(op.f('ix_lead_events_event_type'), table_name='lead_events')
    op.drop_index(op.f('ix_lead_events_created_by'), table_name='lead_events')
    op.drop_index(op.f('ix_lead_events_created_at'), table_name='lead_events')
    op.drop_table('lead_events')
    op.drop_index(op.f('ix_lead_contacts_seniority'), table_name='lead_contacts')
    op.drop_index(op.f('ix_lead_contacts_lead_id'), table_name='lead_contacts')
    op.drop_index(op.f('ix_lead_contacts_email'), table_name='lead_contacts')
    op.drop_table('lead_contacts')
    # ### end Alembic commands ###
