"""PRD V1 full: opportunities sales_messages rbac fields target_countries status migration

Revision ID: d2b1e98f091f
Revises: b20022d59541
Create Date: 2026-08-30 19:29:41.995624

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd2b1e98f091f'
down_revision: str | None = 'b20022d59541'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('expected_close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('won_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_lead_id'), 'opportunities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_opportunities_owner_id'), 'opportunities', ['owner_id'], unique=False)
    op.create_index(op.f('ix_opportunities_stage'), 'opportunities', ['stage'], unique=False)
    op.create_table('sales_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('generated_by', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_messages_created_by'), 'sales_messages', ['created_by'], unique=False)
    op.create_index(op.f('ix_sales_messages_lead_id'), 'sales_messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_sales_messages_reviewed_by'), 'sales_messages', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_sales_messages_status'), 'sales_messages', ['status'], unique=False)
    op.add_column('lead_events', sa.Column('is_alert', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_lead_events_is_alert'), 'lead_events', ['is_alert'], unique=False)
    # JSON NOT NULL 加列必须带 server_default（同 b20022d59541 的处理）
    op.add_column('leads', sa.Column('target_countries', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('leads', sa.Column('export_type', sa.String(length=64), nullable=True))
    op.add_column('leads', sa.Column('field_meta', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('roles', sa.Column('permissions', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('users', sa.Column('data_scope', sa.String(length=16), server_default='all', nullable=False))
    op.add_column('users', sa.Column('team', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_data_scope'), 'users', ['data_scope'], unique=False)
    op.create_index(op.f('ix_users_team'), 'users', ['team'], unique=False)
    # ---- PRD §23：销售状态 6 态 → 10 态数据迁移 ----
    _migrate_follow_status()
    # ---- PRD §42：六个角色的权限码种子（admin 角色已存在则只补权限） ----
    _seed_role_permissions()
    # ### end Alembic commands ###


def _migrate_follow_status() -> None:
    """旧→新状态映射（leads 与 lead_follow_ups 两张表同步）：

    NULL → unassigned（语义不变：共享池）｜pending → pending（待跟进，字面沿用）
    following → contacted｜interested → opportunity
    not_interested / unreachable → invalid｜converted → won
    """
    conn = op.get_bind()
    mapping = {
        "following": "contacted",
        "interested": "opportunity",
        "not_interested": "invalid",
        "unreachable": "invalid",
        "converted": "won",
    }
    for old, new in mapping.items():
        conn.execute(
            sa.text("UPDATE leads SET follow_status = :new WHERE follow_status = :old"),
            {"old": old, "new": new},
        )
        conn.execute(
            sa.text("UPDATE lead_follow_ups SET status = :new WHERE status = :old"),
            {"old": old, "new": new},
        )


def _seed_role_permissions() -> None:
    """PRD §42 六角色权限种子（超管走 is_superuser 旁路，不建角色）。

    admin 已有则补全权限；其余 upsert。
    """
    conn = op.get_bind()
    roles = [
        ("admin", "管理员", ["lead:read", "lead:write", "lead:delete", "assign:lead", "task:manage", "user:manage", "stats:read"]),
        ("sales_manager", "销售主管", ["lead:read", "lead:write", "assign:lead", "stats:read"]),
        ("sales", "销售", ["lead:read", "lead:write"]),
        ("operator", "运营", ["lead:read", "task:manage", "stats:read"]),
        ("data_admin", "数据管理员", ["lead:read", "stats:read"]),
    ]
    import json

    is_pg = conn.dialect.name == "postgresql"
    # PG 需要 CAST(text AS JSON)；SQLite 无 JSON 类型且 CAST AS JSON 会走 NUMERIC
    # 亲和性把字符串变 0，直接存文本（SQLite JSON 列本质就是 TEXT）
    cast = "CAST(:perms AS JSON)" if is_pg else ":perms"
    for code, name, perms in roles:
        existing = conn.execute(
            sa.text("SELECT id FROM roles WHERE code = :code"), {"code": code}
        ).scalar_one_or_none()
        if existing is None:
            conn.execute(
                sa.text("INSERT INTO roles (name, code, permissions, created_at, updated_at) "
                        f"VALUES (:name, :code, {cast}, now(), now())"),
                {"name": name, "code": code, "perms": json.dumps(perms)},
            )
        else:
            conn.execute(
                sa.text(f"UPDATE roles SET permissions = {cast} WHERE code = :code"),
                {"code": code, "perms": json.dumps(perms)},
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_team'), table_name='users')
    op.drop_index(op.f('ix_users_data_scope'), table_name='users')
    op.drop_column('users', 'team')
    op.drop_column('users', 'data_scope')
    op.drop_column('roles', 'permissions')
    op.drop_column('leads', 'field_meta')
    op.drop_column('leads', 'export_type')
    op.drop_column('leads', 'target_countries')
    op.drop_index(op.f('ix_lead_events_is_alert'), table_name='lead_events')
    op.drop_column('lead_events', 'is_alert')
    op.drop_index(op.f('ix_sales_messages_status'), table_name='sales_messages')
    op.drop_index(op.f('ix_sales_messages_reviewed_by'), table_name='sales_messages')
    op.drop_index(op.f('ix_sales_messages_lead_id'), table_name='sales_messages')
    op.drop_index(op.f('ix_sales_messages_created_by'), table_name='sales_messages')
    op.drop_table('sales_messages')
    op.drop_index(op.f('ix_opportunities_stage'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_owner_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_lead_id'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
